### ISSUE TITLE
how to support regression?

### ISSUE THREAD

**Issue by buptzzl** [tobegit3hub/tensorflow_template_application#28] opened 2017-08-16 07:29 UTC

**Comment by tobegit3hub** [comment] 2017-08-17 09:01
It is possible to use TensorFlow API to support regression.

I will update for this after having the dataset for regression.

**Comment by buptzzl** [comment] 2017-08-18 09:43
thanks very much! 
I try myself but the trained model's  MAE  is  too big. I think there is something warn. But I just don't know how to debug the code. 
Waiting for you examples!

**Comment by tobegit3hub** [comment] 2017-09-14 01:08
Now it's supported since https://github.com/tobegit3hub/tensorflow_template_application/commit/f4385ba09b3bc678b0913821f91dea17c5e9f4d6 is merged.

You can follow the REAME.md and try with boston housing dataset firstly.

**Closed as completed by tobegit3hub** 2017-09-14 01:08 UTC
